import os
import shutil
import click
from pathlib import Path
from datetime import datetime
from . import dashboard

@click.group()
def main():
    """Agentic SDLC CLI - Multi-stage software development lifecycle for AI agents."""
    pass

@main.command()
@click.argument('target', default='.', type=click.Path(exists=True, file_okay=False, dir_okay=True))
@click.option('--force', is_flag=True, help="Overwrite existing files.")
def init(target, force):
    """Initialize the Agentic SDLC structure in a target project."""
    target_path = Path(target).resolve()
    click.echo(f"Initializing Agentic SDLC in {target_path}...")

    # 1. Create directory structure
    dirs = [
        "docs/architecture/adrs",
        "docs/architecture/rfcs",
        "docs/product/features",
        "docs/product/mockups",
        "docs/investigations/spikes",
        "docs/sdlc/epics",
        "docs/sdlc/stories",
        "docs/sdlc/workspaces",
        "docs/sdlc/test-plans",
        "docs/sdlc/retrospectives",
    ]
    for d in dirs:
        (target_path / d).mkdir(parents=True, exist_ok=True)
        # Create .gitkeep
        (target_path / d / ".gitkeep").touch()

    # 2. Create stub files
    stubs = [
        ("docs/architecture/domain-model.md", "Domain Knowledge", "asdlc-inception"),
        ("docs/product/features/brd.md", "Business Requirements", "asdlc-inception"),
        ("docs/product/design-system.md", "Design System", "asdlc-design-system"),
        ("docs/product/mockups.md", "UI Mockups", "asdlc-ui-mockups"),
        ("docs/product/personas.md", "Personas", "asdlc-inception"),
        ("docs/architecture/tech-architecture.md", "Technical Architecture", "asdlc-tech-architecture"),
        ("docs/architecture/coding-standards.md", "Coding Constitution", "asdlc-tech-architecture"),
        ("docs/sdlc/epics/implementation-plan.md", "Implementation Plan", "asdlc-implementation-planning"),
        ("docs/architecture/data-domain.md", "Interface Contracts", "asdlc-implementation-planning"),
        ("docs/product/accessibility.md", "Accessibility Requirements", "asdlc-design-system"),
        ("docs/architecture/existing-system.md", "Existing System Analysis", "asdlc-context-harvest"),
    ]

    for file_rel, title, stage in stubs:
        file_path = target_path / file_rel
        if not file_path.exists() or force:
            with open(file_path, 'w') as f:
                f.write(f"# {title}\n\n")
                f.write(f"> **Status:** Not started\n")
                f.write(f"> **Stage:** {stage}\n")
                f.write(f"> **Version:** 0.1.0\n")
                f.write(f"> **Last updated:** {datetime.now().strftime('%Y-%m-%d')}\n\n")
                f.write(f"_This file is generated by the agentic-sdlc framework._\n")
                f.write(f"_Populate it by following the {stage} skill._\n")
            click.echo(f"  Created {file_rel}")

    # 3. Copy skills, templates, and core files from package
    package_root = Path(__file__).parent
    
    # Copy skills
    if (target_path / ".agents" / "skills").exists() and not force:
        click.echo("  Skill directory already exists. Use --force to overwrite.")
    else:
        if (target_path / ".agents" / "skills").exists():
            shutil.rmtree(target_path / ".agents" / "skills")
        shutil.copytree(package_root / "skills", target_path / ".agents" / "skills")
        click.echo("  Copied skills directory.")

    # Copy core files (only AGENTS.md)
    core_file = package_root / "core" / "AGENTS.md"
    dest = target_path / "AGENTS.md"
    if not dest.exists() or force:
        shutil.copy(core_file, dest)
        click.echo("  Copied AGENTS.md")

    click.echo("\nDone! Agentic SDLC is ready.")
    click.echo("Next steps:")
    click.echo("  1. Instruct your agent: 'Read AGENTS.md and .agents/skills/asdlc-using-agentic-sdlc/SKILL.md'")
    click.echo("  2. Start with 'asdlc-inception' (greenfield) or 'asdlc-context-harvest' (brownfield)")

@main.command()
@click.argument('target', default='.', type=click.Path(exists=True, file_okay=False, dir_okay=True))
def update_agents(target):
    """Update AGENTS.md with Phase 2 project context."""
    target_path = Path(target).resolve()
    agents_path = target_path / "AGENTS.md"
    if not agents_path.exists():
        click.echo("AGENTS.md not found in project root. Run 'asdlc init' first.", err=True)
        return

    click.echo(f"Updating '{agents_path}' with project context...")
    
    # Read context files
    tech_arch = target_path / "docs" / "architecture" / "tech-architecture.md"
    coding_standards = target_path / "docs" / "architecture" / "coding-standards.md"

    context_block = "\n## Project Context (Phase 2)\n\nThis section contains project-specific context established during the Tech Architecture stage.\n\n"
    if tech_arch.exists():
        context_block += f"- **Tech Stack**: Refer to [{tech_arch.name}]({tech_arch.relative_to(target_path)})\n"
        context_block += f"- **Directory Structure**: Refer to [{tech_arch.name}]({tech_arch.relative_to(target_path)})\n"
    else:
        context_block += "- **Tech Stack & Architecture**: Not yet defined.\n"

    if coding_standards.exists():
        context_block += f"- **Coding Standards**: Refer to [{coding_standards.name}]({coding_standards.relative_to(target_path)})\n"

    with open(agents_path, "a") as f:
        f.write(context_block)
        
    click.echo("Added Phase 2 Project Context to AGENTS.md")

@main.command()
@click.argument('project_root', default='.')
@click.option('--port', default=8080, help="Port to serve the dashboard on.")
def serve(project_root, port):
    """Start the Agnetic SDLC dashboard."""
    dashboard.serve(project_root, port)


@click.group()
def dev_main():
    """Agentic SDLC Developer CLI - includes eval and validation tools."""
    pass

# Register all public commands on dev_main too
dev_main.add_command(init)
dev_main.add_command(serve)
dev_main.add_command(update_agents)


@dev_main.command('validate-skills')
@click.argument('repo_root', default='.', type=click.Path(exists=True, file_okay=False, dir_okay=True))
@click.option('--json-output', 'json_output', is_flag=True, default=False,
              help='Emit results as JSON instead of human-readable text.')
def validate_skills(repo_root, json_output):
    """Validate all SKILL.md files for structural correctness and consistency."""
    import json
    import sys
    from .eval import validator as skill_validator

    root = Path(repo_root).resolve()
    report = skill_validator.validate(root)

    if json_output:
        click.echo(json.dumps(report.as_dict(), indent=2))
    else:
        status = "PASS" if report.ok else "FAIL"
        click.echo(f"validate-skills: {status} ({report.checks_run} checks, "
                   f"{len(report.errors)} errors, {len(report.warnings)} warnings)")
        for issue in report.errors:
            loc = f":{issue.line}" if issue.line else ""
            click.echo(f"  ERROR  [{issue.rule_id}] {issue.path}{loc} — {issue.message}")
        for issue in report.warnings:
            loc = f":{issue.line}" if issue.line else ""
            click.echo(f"  WARN   [{issue.rule_id}] {issue.path}{loc} — {issue.message}")

    sys.exit(0 if report.ok else 1)


@dev_main.command('eval-skills')
@click.argument('repo_root', default='.', type=click.Path(exists=True, file_okay=False, dir_okay=True))
@click.option('--skill', default=None, help='Only eval fixtures for this skill name.')
@click.option('--fixtures', 'fixtures_dir', default=None,
              help='Path to fixtures directory. Defaults to <repo_root>/fixtures.')
@click.option('--json-output', 'json_output', is_flag=True, default=False,
              help='Emit results as JSON instead of human-readable text.')
def eval_skills(repo_root, skill, fixtures_dir, json_output):
    """Run deterministic scenario fixtures against selected skills."""
    import json
    import sys
    from .eval import harness as skill_harness

    root = Path(repo_root).resolve()
    fixtures_root = Path(fixtures_dir).resolve() if fixtures_dir else root / 'fixtures'

    if not fixtures_root.exists():
        package_fixtures = Path(__file__).parent / 'fixtures'
        if package_fixtures.exists():
            fixtures_root = package_fixtures

    if not fixtures_root.exists():
        click.echo(f"eval-skills: fixtures directory not found: {fixtures_root}", err=True)
        sys.exit(1)

    report = skill_harness.run(root, fixtures_root, skill_filter=skill)

    if json_output:
        click.echo(json.dumps(report.as_dict(), indent=2))
    else:
        status = "PASS" if report.ok else "FAIL"
        click.echo(f"eval-skills: {status} ({report.scenarios_run} scenarios, "
                   f"{report.passed} passed, {report.failed} failed)")
        for result in report.results:
            if not result.ok:
                click.echo(f"  FAIL [{result.scenario_id}] skill={result.skill}")
                for failure in result.failures:
                    click.echo(f"       - {failure}")

    sys.exit(0 if report.ok else 1)


if __name__ == "__main__":
    main()
