import os
import shutil
import click
from pathlib import Path
from datetime import datetime
from . import dashboard

@click.group()
def main():
    """Agentic SDLC CLI - Multi-stage software development lifecycle for AI agents."""
    pass

@main.command()
@click.argument('target', default='.', type=click.Path(exists=True, file_okay=False, dir_okay=True))
@click.option('--force', is_flag=True, help="Overwrite existing files.")
def init(target, force):
    """Initialize the Agentic SDLC structure in a target project."""
    target_path = Path(target).resolve()
    click.echo(f"Initializing Agentic SDLC in {target_path}...")

    # 1. Create directory structure
    dirs = [
        "docs/architecture/adrs",
        "docs/architecture/rfcs",
        "docs/product/features",
        "docs/investigations/spikes",
        "docs/sdlc/epics",
        "docs/sdlc/stories",
        "docs/sdlc/workspaces",
        "docs/sdlc/test-plans",
        "docs/sdlc/retrospectives",
    ]
    for d in dirs:
        (target_path / d).mkdir(parents=True, exist_ok=True)
        # Create .gitkeep
        (target_path / d / ".gitkeep").touch()

    # 2. Create stub files
    stubs = [
        ("docs/architecture/domain-model.md", "Domain Knowledge", "inception"),
        ("docs/product/features/brd.md", "Business Requirements", "inception"),
        ("docs/product/design-system.md", "Design System", "design-system"),
        ("docs/product/personas.md", "Personas", "inception"),
        ("docs/architecture/tech-architecture.md", "Technical Architecture", "tech-architecture"),
        ("docs/architecture/coding-standards.md", "Coding Constitution", "tech-architecture"),
        ("docs/sdlc/epics/implementation-plan.md", "Implementation Plan", "implementation-planning"),
        ("docs/architecture/data-domain.md", "Interface Contracts", "implementation-planning"),
        ("docs/product/accessibility.md", "Accessibility Requirements", "design-system"),
        ("docs/architecture/existing-system.md", "Existing System Analysis", "context-harvest"),
    ]

    for file_rel, title, stage in stubs:
        file_path = target_path / file_rel
        if not file_path.exists() or force:
            with open(file_path, 'w') as f:
                f.write(f"# {title}\n\n")
                f.write(f"> **Status:** Not started\n")
                f.write(f"> **Stage:** {stage}\n")
                f.write(f"> **Last updated:** {datetime.now().strftime('%Y-%m-%d')}\n\n")
                f.write(f"_This file is generated by the agentic-sdlc framework._\n")
                f.write(f"_Populate it by following the {stage} skill._\n")
            click.echo(f"  Created {file_rel}")

    # 3. Copy skills, templates, and core files from package
    package_root = Path(__file__).parent
    
    # Copy skills
    if (target_path / "skills").exists() and not force:
        click.echo("  Skill directory already exists. Use --force to overwrite.")
    else:
        if (target_path / "skills").exists():
            shutil.rmtree(target_path / "skills")
        shutil.copytree(package_root / "skills", target_path / "skills")
        click.echo("  Copied skills directory.")

    # Copy templates
    if (target_path / "templates").exists() and not force:
        click.echo("  Templates directory already exists. Use --force to overwrite.")
    else:
        if (target_path / "templates").exists():
            shutil.rmtree(target_path / "templates")
        shutil.copytree(package_root / "templates", target_path / "templates")
        click.echo("  Copied templates directory.")

    # Copy core files (AGENTS.md, etc.)
    for core_file in (package_root / "core").glob("*.md"):
        dest = target_path / core_file.name
        if not dest.exists() or force:
            shutil.copy(core_file, dest)
            click.echo(f"  Copied {core_file.name}")

    click.echo("\nDone! Agentic SDLC is ready.")
    click.echo("Next steps:")
    click.echo("  1. Instruct your agent: 'Read AGENTS.md and skills/using-agentic-sdlc/SKILL.md'")
    click.echo("  2. Start with 'inception' (greenfield) or 'context-harvest' (brownfield)")

@main.command()
@click.argument('project_root', default='.')
@click.option('--port', default=8080, help="Port to serve the dashboard on.")
def serve(project_root, port):
    """Start the Agnetic SDLC dashboard."""
    dashboard.serve(project_root, port)

if __name__ == "__main__":
    main()
