#!/usr/bin/env bash
# init-context.sh — Initialize the /.agentic-sdlc/ context directory in a project
#
# Usage: bash scripts/init-context.sh [target-dir]
#   target-dir: path to the project root (default: current directory)
#
# Example: bash scripts/init-context.sh /path/to/my-project

set -euo pipefail

TARGET="${1:-.}"

if [ ! -d "$TARGET" ]; then
  echo "Error: target directory '$TARGET' does not exist."
  exit 1
fi

CTX="$TARGET/.agentic-sdlc"

echo "Initializing agentic-sdlc context directory at: $CTX"

mkdir -p "$CTX/adr"

# Create stub files with minimal frontmatter
create_stub() {
  local file="$1"
  local title="$2"
  local stage="$3"
  if [ ! -f "$file" ]; then
    cat > "$file" << EOF
# $title

> **Status:** Not started
> **Stage:** $stage
> **Last updated:** $(date +%Y-%m-%d)

_This file is generated by the agentic-sdlc framework._
_Populate it by following the $stage skill._
EOF
    echo "  Created: $file"
  else
    echo "  Skipped (exists): $file"
  fi
}

create_stub "$CTX/domain.md"             "Domain Knowledge"         "inception"
create_stub "$CTX/brd.md"               "Business Requirements"     "inception"
create_stub "$CTX/design-system.md"     "Design System"             "design-system"
create_stub "$CTX/accessibility.md"     "Accessibility Requirements" "design-system"
create_stub "$CTX/tech-architecture.md" "Technical Architecture"    "tech-architecture"
create_stub "$CTX/coding-constitution.md" "Coding Constitution"     "tech-architecture"
create_stub "$CTX/implementation-plan.md" "Implementation Plan"     "implementation-planning"
create_stub "$CTX/interface-contracts.md" "Interface Contracts"     "implementation-planning"
create_stub "$CTX/task-graph.md"        "Task Graph"               "story-breakdown"
create_stub "$CTX/test-plan.md"         "Test Plan"                "testing"
create_stub "$CTX/critical-review.md"   "Critical Review"          "critical-review"
create_stub "$CTX/retrospective.md"     "Retrospective"            "retrospective"

# Brownfield only
create_stub "$CTX/existing-system.md"   "Existing System Analysis" "context-harvest"

# Create a .gitkeep in adr/ so git tracks it
touch "$CTX/adr/.gitkeep"
echo "  Created: $CTX/adr/ (with .gitkeep)"

echo ""
echo "Done! Context directory ready at: $CTX"
echo ""
echo "Next steps:"
echo "  Greenfield: Read skills/using-agentic-sdlc/SKILL.md, then skills/inception/SKILL.md"
echo "  Brownfield: Read skills/using-agentic-sdlc/SKILL.md, then skills/context-harvest/SKILL.md"
